name: Build and push docker image

on:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login ghcr
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: docker login ghcr.io --username iwa --password "$GHCR_TOKEN"
      - name: Build and Push Image
        run: |
          docker buildx build \
                  --tag ghcr.io/iwa/skinpeek:latest \
                  --platform linux/amd64,linux/arm64/v8 \
                  --file ./Dockerfile \
                  --output type=image,push=true .
