name: Build and push docker image

on:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Install Node v18
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and Push Image
        run: |
          docker buildx build \
                  --tag ghcr.io/iwa/skinpeek:latest \
                  --platform linux/amd64,linux/arm64/v8 \
                  --file ./Dockerfile \
                  --output type=image,push=true .
